name: API Lint & Test
on:
  pull_request:
    paths:
      - 'api/**'

permissions:
  contents: read

jobs:
  api-v1:
    name: api/v1
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api/v1
    steps:
      - uses: actions/checkout@v4
      - uses: buildjet/setup-go@v5
        with:
          go-version: 1.25.x
      - run: make lint
      - run: make test

  api-plugin:
    name: api/plugin
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api/plugin
    steps:
      - uses: actions/checkout@v4
      - uses: buildjet/setup-go@v5
        with:
          go-version: 1.25.x
      - run: make lint
      - run: make test
